networks:
  redis-network:
    external: true

x-replica-common: &replica-common
    image: redis:latest
    depends_on:
      - redis-master
    command: ["redis-server", "--replicaof", "172.23.0.10", "6379"]

x-sentinel-common: &sentinel-common 
    build: ./sentinel
    depends_on:
      - redis-master
      - redis-replica1
      - redis-replica2
    command: ["redis-server", "/usr/local/etc/redis/sentinel.conf", "--sentinel"]


services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    hostname: redis-master
    networks:
      redis-network:
        ipv4_address: 172.23.0.10
    # ports:
    #   - "6379:6379"
    volumes:
      - ./master/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis-replica1:
    <<: *replica-common
    container_name: redis-replica1
    networks:
      redis-network:
        ipv4_address: 172.23.0.11

  redis-replica2:
    <<: *replica-common
    container_name: redis-replica2
    networks:
      redis-network:
        ipv4_address: 172.23.0.12

  redis-sentinel-1:
    <<: *sentinel-common
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    networks:
      redis-network:
        ipv4_address: 172.23.0.21

  redis-sentinel-2:
    <<: *sentinel-common
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"
    networks:
      redis-network:
        ipv4_address: 172.23.0.22

  redis-sentinel-3:
    <<: *sentinel-common
    container_name: redis-sentinel-3
    ports:
      - "26381:26379"
    networks:
      redis-network:
        ipv4_address: 172.23.0.23

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    networks:
      redis-network:
        ipv4_address: 172.23.0.24
